### ISSUE TITLE
[1.19.4] Ransomware detection by Malwarebytes

### ISSUE THREAD

**Issue by Pegietix** [MC-U-Team/U-Team-Core#390] opened 2024-02-23 16:32 UTC
### Bug description and reproduction steps

Not sure if it's this mod or Useful Railroads, but one of them is causing jawav.exe to be blocked by malwarebytes after few minutes of playing singleplayer world, because of ransomware detection.

### Log files and Screenshots

![ransomware](https://github.com/MC-U-Team/U-Team-Core/assets/37411436/a4d08dc2-c126-41ce-9659-ff5925cc1c4e)

### Used minecraft version

1.19.x

### Used forge or fabric version

45.0.57

### Used mod version

5.0.2.250

**Comment by HyCraftHD** [comment] 2024-03-04 16:41
Hi.
Virus Total shows no detection at all:

https://www.virustotal.com/gui/file/b845a56f15b777335081ca277d884947b43ea423e19e5aad767fd86a37fe8b54/detection

https://www.virustotal.com/gui/file/69c09a864a96b8c9486e665e514289046f8675555d19a233c02418ba6b4a01f7/detection

Might have been a false positive that is fixed now.
Closing as it seems to be not caused by uteamcore or useful backpacks.

**Closed as not planned by HyCraftHD** 2024-03-04 16:41 UTC
Labels: bug
