### ISSUE TITLE
uteamcore makes game crash on startup

### ISSUE THREAD

**Issue by ajw2004** [MC-U-Team/U-Team-Core#12] opened 2018-07-17 18:00 UTC
when ever i try to use uteamcore my game crashes and i get this error Error: java.lang.NoSuchMethodError: info.u_team.u_team_core.sub.USubMod.(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
how do i fix this

**Comment by HyCraftHD** [comment] 2018-07-17 18:02
Please update all mods that require uteamcore, like usefulbackpacks to the newest version.

Duplicate of #11

**Closed as completed** 2018-07-22 13:27 UTC
Labels: bug, duplicate
