### ISSUE TITLE
[1.14.4] Channels [uteamcore:network] rejected their server side version number[MC-Version] Bug short description

### ISSUE THREAD

**Issue by SDUBZ** [MC-U-Team/U-Team-Core#27] opened 2019-12-27 21:44 UTC
**Describe the bug**
joining virtual server the clients version is rejected

**To Reproduce**
1. Go to join server that both has u_team_core-1.14.4-2.8.0.140 and forge 1.14.4-107
2. start joining server
3. get kicked from server

**Expected behavior**

**Screenshots**

**Versions**
- Minecraft version: 1.14.4
- Forge version: 107
- UTeamCore version: 1.14.4-140

**Log (if crash occures)**
client:
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4006314/latest.log)
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/4006315/debug.log)

**Comment by HyCraftHD** [comment] 2019-12-27 21:59
Thanks for the report. Can you please link the server and client debug log. I don't really know what log is for which side. Also please define virtual server

**Comment by SDUBZ** [comment] 2019-12-27 22:26
okay edited and i will post server logs in a sec
server logs: 
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/4006383/debug.log)
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4006384/latest.log)

**Comment by HyCraftHD** [comment] 2019-12-27 22:37
Please linke the client logs too

**Comment by HyCraftHD** [comment] 2019-12-27 22:43
Please send me the client log. The log you provided above are both the server logs

**Comment by SDUBZ** [comment] 2019-12-28 20:24
its there in original part the client logs

**Comment by HyCraftHD** [comment] 2019-12-28 20:25
No this is also a server log. It loads the mods from here: E:\FORGE SERVER

**Comment by HyCraftHD** [comment] 2019-12-28 20:26
Also do not edit comments just paste a new comment with both logs please. Otherwise it becomes very confusing.

**Comment by SDUBZ** [comment] 2019-12-28 20:27
oh sorry must of been tired or something will post logs soon

**Comment by SDUBZ** [comment] 2019-12-28 21:21
client :
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4007471/latest.log)
server:
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/4007474/debug.log)
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4007475/latest.log)

**Comment by HyCraftHD** [comment] 2019-12-28 22:20
Thanks for the logs.

I tested it with these versions:
 - Forge: 28.1.107
 - Uteamcore: 2.8.0.140
 - Usefulbackpacks: 1.7.4.47

I cannot reproduce this bug by using these versions. I assume you are using any other versions or an other mod has a problem.
Can you try to download these versions without any other mod and test it?

The client log also rejects the embellishcraft:embellishcraft_channel network. Maybe try to remove that mod for testing.

**Comment by SDUBZ** [comment] 2019-12-28 23:27
i can try those i am using that version of useful back packs also

**Comment by SDUBZ** [comment] 2019-12-29 00:05
Channels [uteamcore:network] rejected their server side version number during listping
same thing happens with embellishcraft disabled
client:
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4007595/latest.log)
server:
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/4007596/debug.log)
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4007597/latest.log)

**Comment by HyCraftHD** [comment] 2019-12-29 00:08
Well than it can only be a mismatch or a strange bug between the server and client version. Can you try to install these jars on the server and client and try again? The strange thing is I cannot replicate that bug in any way :/



[mods.zip](https://github.com/MC-U-Team/U-Team-Core/files/4007600/mods.zip)

**Comment by HyCraftHD** [comment] 2019-12-29 00:10
Also can you send me the client and server jar of uteamcore that you have installed? (You must zip it to upload it to github)

**Comment by SDUBZ** [comment] 2019-12-29 01:42
okay can do

**Comment by SDUBZ** [comment] 2019-12-29 01:46
[uteam.zip](https://github.com/MC-U-Team/U-Team-Core/files/4007656/uteam.zip)
client and server versions in their respectable folder :)

**Comment by HyCraftHD** [comment] 2019-12-29 14:06
Tested it with your version and everything worked fine..
Can you setup a server and a client with only forge and uteamcore installed and then try to connect?
Also if that works can you send me your whole server and client modpack?

**Comment by SDUBZ** [comment] 2019-12-31 01:51
okay i updated mods and now its fixed but im getting a weird javaio exception on playerdata or world not sure how to tackle this bug

**Comment by HyCraftHD** [comment] 2019-12-31 02:03
Well the playerdata is untouched from any mod I did for 1.14.4 so this must be an issue with an other mod or because you removed some mods that the world required.

**Comment by HyCraftHD** [comment] 2020-01-04 16:02
I'll close this issue for now as it seems to be fixed. Please report if it happens again.

**Closed as completed by HyCraftHD** 2020-01-04 16:02 UTC
Labels: bug
